### ISSUE TITLE
code for NIV

### ISSUE THREAD

**Issue by Ravindu-Yasas-Nagasinghe** [nonozhizhiovo/skipplan#2]
The provided trainng code is for CrossTask dataset only. Can you please provide a training code that works for NIV dataset as well.

**Comment by nonozhizhiovo** [comment]
Thanks for your interest in our work. 

Unfortunately, we didn't train and test on NIV dataset (as u see in paper), so i am afraid we cannot provide you the training code of this dataset. 

Best regards,
Zhiheng
